services:
  - type: web
    name: iq-trader
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
